###
POST localhost:8081/products
Content-Type: application/json

{
  "name": "Ложка для обуви",
  "price": 100000,
  "quantity": 15
}

###
GET localhost:8081/products?productName=
Content-Type: application/json

###
PUT localhost:8081/products
Content-Type: application/json

{
  "id": 2,
  "name": "Спальный мешок",
  "price": 800,
  "quantity": 15
}

###
DELETE localhost:8081/products/1

###
POST localhost:8081/clients
Content-Type: application/json

{
  "name": "Павел",
  "login": "pavel123",
  "password": "password123",
  "email": "pavel@yandex.ru"
}

###
GET localhost:8081/clients/1
Content-Type: application/json

###
DELETE localhost:8081/clients/2

###
POST localhost:8081/carts/3/products/6

###
PUT localhost:8081/carts/3/products/3
Content-Type: application/json

{
"quantity": 5
}

###
DELETE localhost:8081/carts/3/products/3

###
POST localhost:8081/carts/payment/3

###
GET localhost:8081/carts/1
Content-Type: application/json
