###Добавление клиента
POST localhost:8081/users
Content-Type: application/json

{
  "email": "123@yandex.ru",
  "username": "Павел",
  "password": "123"
}

###Получение клиента
GET localhost:8081/users/4
Content-Type: application/json

###Удаление клиента
DELETE localhost:8081/users/7